id: I412448A2
legacy_id: P003301
ocr_import_info:
  bdrc_scan_id: W00KG08430
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T02:13:31'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:23:49.816844+00:00'
last_modified: 2022-08-29 20:26:01.745209
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG08430
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG08430
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། བློ་བཟང་དཔལ་ལྡན།
  author: ཡོངས་འཛིན་པཎཌི་ཏ་བློ་བཟང་དཔལ་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.9337551911852033
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG08438:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG08438
      total_pages: 616
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00KG08438.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9116037004342036
    legacy_id: v003
  I00KG08437:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG08437
      total_pages: 576
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00KG08437.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9451926647726104
    legacy_id: v002
  I00KG08436:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG08436
      total_pages: 608
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG08436.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9415239104177673
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
