id: P003301
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG08430
  title: གསུང་ཐོར་བུ། བློ་བཟང་དཔལ་ལྡན
  author: ''
  volumes:
    fe26df5e51b14b0497534a2fe5de5bef:
      image_group_id: I00KG08436
      title: ''
      volume_number: 1
      total_pages: 608
      base_file: v001.txt
    fb89417306284b87bf0d4b7f441f0a4e:
      image_group_id: I00KG08437
      title: ''
      volume_number: 2
      total_pages: 576
      base_file: v002.txt
    792b0bf100f9488ba99bcdd92a2ff909:
      image_group_id: I00KG08438
      title: ''
      volume_number: 3
      total_pages: 616
      base_file: v003.txt
